import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Generated from the folder structure of the content repo, so adding a page there needs no change
 * here. Ordering comes from `sidebar_position` in front matter and `_category_.json`.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
